import Navbar from "../components/Navbar";
import {Roboto} from "next/font/google";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  style:["normal","italic"],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
